version: 2
updates:
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: weekly
  target-branch: dev-marcel

- package-ecosystem: uv
  directory: /
  schedule:
    interval: weekly
  target-branch: dev-marcel

- package-ecosystem: pre-commit   # hook revisions in .pre-commit-config.yaml
  directory: /
  schedule:
    interval: weekly
  target-branch: dev-marcel
